import type { StoreConfig } from '@stores/types';

/**
 * Lush (Salesforce Commerce Cloud).
 *
 * Primary signal: the Schema.org `Product` JSON-LD in the page head, e.g.
 *   {"@type":"Product","offers":{"@type":"Offer","availability":"https://schema.org/InStock"}}
 * Fallback: the product call-to-action button text (`Añadir a la cesta` /
 * `No disponible`), used when no usable JSON-LD is present.
 */
export const lushStore: StoreConfig = {
  domain: 'lush.com',
  name: 'Lush',
  strategies: [
    { type: 'jsonld' },
    {
      type: 'htmlSelector',
      // The button class names are generated by styled-components, so match any
      // button and compare its text instead of relying on an unstable class.
      selector: 'button',
      inStockText: 'Añadir a la cesta',
      outOfStockText: 'No disponible',
    },
  ],
};
